name = "sentinelchain"
main = "worker/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "sentinelchain-db"
database_id = "0c56ddf8-28bd-4be5-88e0-a3c75811753c"

[build]
upload = { format = "modules" }
